changeLogFile: db.changelog.xml
url: jdbc:postgresql://liquibase-poc-db.cmhc6iiygnwr.us-east-1.rds.amazonaws.com:5432/postgres
username: admin
password: saitejaadmin
driver: org.postgresql.Driver
classpath: /usr/lib/liquibase/postgresql.jar
