version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Downloading Liquibase CLI..."
      - wget https://github.com/liquibase/liquibase/releases/download/v4.27.0/liquibase-4.27.0.zip
      - unzip liquibase-4.27.0.zip -d liquibase
      - sudo mv liquibase /usr/local/bin
      - chmod +x /usr/local/bin/liquibase/liquibase
      - echo "Downloading PostgreSQL driver..."
      - wget https://jdbc.postgresql.org/download/postgresql-42.7.2.jar
  build:
    commands:
      - echo "Running Liquibase migration..."
      - /usr/local/bin/liquibase/liquibase --defaultsFile=liquibase.properties update
